CREATE TABLE posts (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  uuid VARCHAR(8) NOT NULL UNIQUE,
  parent_id INTEGER,
  poster_id INTEGER NOT NULL,
  body VARCHAR(1024) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  reply_count INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(poster_id) REFERENCES users(id),
  FOREIGN KEY(parent_id) REFERENCES posts(id)
);