CREATE TABLE attachments (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    uploader_id INTEGER NOT NULL,
    uuid VARCHAR(8) NOT NULL UNIQUE,
    file_name VARCHAR(256) NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY(uploader_id) REFERENCES users(id)
);