CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  email VARCHAR(256) NOT NULL UNIQUE,
  real_name VARCHAR(256) NOT NULL,
  summary VARCHAR(1024) NOT NULL,
  password VARCHAR(256) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);